api_platform:
#    mapping:
#        paths: ['%kernel.project_dir%/config/api_platform']
    swagger:
        api_keys:
            JWT:
               name: Authorization
               type: header

