# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
imports:
  - {resource: 'services.php'}
parameters:


# config/services.yaml
services:
    Symfony\Component\Uid\Command\GenerateUlidCommand: ~
    Symfony\Component\Uid\Command\GenerateUuidCommand: ~
    Symfony\Component\Uid\Command\InspectUlidCommand: ~
    Symfony\Component\Uid\Command\InspectUuidCommand: ~
    Symfony\Component\Uid\Command\GenerateUlidCommand:
      public: true
    Symfony\Component\Uid\Command\GenerateUuidCommand:
      public: true
    Symfony\Component\Uid\Command\InspectUlidCommand:
      public: true
    Symfony\Component\Uid\Command\InspectUuidCommand:
      public: true
    order.commodity.update:
      alias: App\Service\UpdateOrderCommodityService
    order.commodity.create:
      alias: App\Service\RelevantCommodityService
    order.update:
      alias: App\Service\UpdateOrderHandler
    order.commodity.factory:
      alias: App\Service\CommodityFactory
    order.entity.updater:
      alias: App\Service\OrderUpdater
    products.get.finder:
      alias: App\Service\ProductFinder
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true 
        # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Convertors\MediaNormalizer:
      public: true
      tags: ['serializer.normalizer']
    App\State\UserHashProcessor:
        public: true
        bind:
            $processor: '@api_platform.doctrine.orm.state.persist_processor'
#    App\Service\RelevantCommodityService:
#        public: true
    App\Controller\ProductAction:
      bind:
        App\Service\Finder: '@products.get.finder'

    App\Controller\OrderAction:
      bind:
#        App\Service\CommodityDefiner: '@order.commodity.create'
        App\Service\OrderHandler: '@order.update'
        App\Service\CFactory: '@order.commodity.factory'
    App\Controller\UpdateOrderAction:
      bind:
        App\Service\OrderHandler: '@order.update'
        App\Service\CFactory: '@order.commodity.factory'
        App\Service\OrderFactory: '@order.entity.updater'
#        App\Service\CommodityDefiner: '@order.commodity.create'

#imports:
#  - { resource: 'services.php' }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
